In [1]:
import numpy as np

In [2]:
array = np.array([20,40,50,60,100])
print("Numpy Array:")
print(array)

Numpy Array:
[ 20  40  50  60 100]


In [5]:
print("\n Shape of numpy array:")
print(array.shape)


 Shape of numpy array:
(5,)


In [6]:
import pandas as pd

In [7]:
mithra = pd.Series([1000,2000,3000,4000,5000,7000])
print(mithra)

0    1000
1    2000
2    3000
3    4000
4    5000
5    7000
dtype: int64


In [12]:
mithra = np.array([20,20,30,40,50,60,70,80,90,100])
print("Numpy Array:")
print(mithra)

Numpy Array:
[ 20  20  30  40  50  60  70  80  90 100]


In [14]:
mithra = np.array([[20,20,30,40,50],[60,70,80,90,100]])
print("Numpy Array:")
print(mithra)

Numpy Array:
[[ 20  20  30  40  50]
 [ 60  70  80  90 100]]


In [16]:
mithra = np.zeros((4,5))
vintha = np.zeros(10)
print(mithra)
print(vintha)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
mithra = np.ones((5,4))
vintha = np.ones(20)
print(mithra)
print(vintha)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
